config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :cars do
  	resources :bookings
  end

  root 'cars#index'
end

app/models/booking.rb
class Booking < ActiveRecord::Base
	belongs_to :car
	belongs_to :user
	validates :customer_name, presence: true
	validate :date_validation

	private
	def date_validation
		errors.add(:booked_from, "is not available") unless Booking.where("? >= booked_from AND ? <= booked_to",
															booked_from, booked_from).where("? = car_id", car_id).count == 0
		errors.add(:booked_to, "is not available") unless Booking.where("? >= booked_from AND ? <= booked_to",
															booked_to, booked_to).where("? = car_id", car_id).count == 0
	end
end

app/models/car.rb
class Car < ActiveRecord::Base

	belongs_to :category
	belongs_to :user
	has_many :bookings


	has_attached_file :image, styles: { :medium => "500x500#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/


	validates :name, presence: true
	validates :description, presence: true

end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :cars
	
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cars

  has_many :bookings

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :set_car

  def index
    @bookings = Booking.all
  end

  def show
  end

  def new
    @booking = current_user.bookings.build
  end

  def edit
    
  end

  def create
    @booking = current_user.bookings.build(booking_params)
    @booking.car_id = @car.id

      if @booking.save
        redirect_to @car, notice: 'Booking was successfully created.'
      else
        render :new
      end
    
  end

  def update
      @booking.car_id = @car.id
      if @booking.update(booking_params)
        redirect_to @car, notice: 'Booking was successfully updated.'
      else
        render :edit
      end
    
  end

  def destroy
    @booking.destroy
    redirect_to @car, notice: 'Booking was successfully destroyed.'

  end

  private
    def set_booking
      @booking = Booking.find(params[:id])
    end

    def set_car
      @car = Car.find(params[:car_id])
    end

    def booking_params
      params.require(:booking).permit(:customer_name, :comment, :booked_from, :booked_to, :price)
    end
    
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
	before_action :find_car, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]


	def index
		if params[:category].blank?
			@cars = Car.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@cars = Car.where(category_id: @category_id).order("created_at DESC")
		end
		@bookings = Booking.all
	end

	def show
		@bookings = Booking.where(car_id: @car.id).order("created_at DESC")
	end

	def new
		@car = current_user.cars.build
	end

	def create
		@car = current_user.cars.build(car_params)

		if @car.save
			redirect_to @car, notice: "Succesfully created new car"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @car.update(car_params)
			redirect_to @car, notice: "Car was succesfully updated!"
		else
			render 'edit'
		end

	end

	def destroy
		@car.destroy
		@bookings = @car.bookings.where(car_id: @car.id)
		@bookings.destroy_all
		redirect_to root_path
	end

	private

	def car_params
		params.require(:car).permit(:name, :description, :category_id, :image)
	end

	def find_car
		@car = Car.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/bookings/_form.html.haml
= simple_form_for([@car,@booking]) do |f|
	.form-group
		= f.input :customer_name
		= f.input :comment
		= f.input :booked_from
		= f.input :booked_to
		= f.button :submit

app/views/bookings/edit.html.haml
%h1 Edit Booking

= render 'form'


=link_to "Back", car_path(@car), class: "btn btn-default"

app/views/bookings/new.html.haml
%h1 New Booking

= render 'form'

=link_to "Back", car_path(@car), class: "btn btn-default"

app/views/bookings/show.html.haml
%h2= @booking.customer_name 
= @booking.comment
%h1= @booking.booked_from.strftime("%F")
%h1= @booking.booked_to.strftime("%F")

app/views/cars/_form.html.haml
.col-md-6.col-md-offset-3
= simple_form_for @car,html: {multipart: true } do |f|
	.form-group
		= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose a category"}
		= f.input :name
		= f.input :description
		= f.input :image, as: :file
		= f.button :submit

app/views/cars/edit.html.haml
.col-md-6.col-md-offset-3
	%h1 Edit car
	= image_tag @car.image.url(:medium)
	= render 'form'

	= link_to "cancel", car_path, class: "btn btn-default"

app/views/cars/index.html.haml
#cars
	- @cars.each do |car|
		.car
			.car_image
				= link_to (image_tag car.image.url), car
			.car_info
				.title
					%h1= link_to car.name, car			
				- @bookings.where(car_id: car.id).each do |booking|
					-if Time.now>=booking.booked_from && Time.now<=booking.booked_to
						%h2 NOT AVAILABLE

app/views/cars/new.html.haml
.col-md-6.col-md-offset-3
	.row
		.panel.panel-default
			.panel-heading
			
				%h1 New Car


				= render 'form'

				= link_to "Back", root_path, class: "btn btn-default"

app/views/cars/show.html.haml
#cars_show.row
	.col-md-8.col-md-offset-2
		.panel.panel-default
			.panel-heading.car_image

				= image_tag @car.image.url(:medium)

			.panel-body

				%h1= @car.name
				%p= @car.description
				%p created by:  
				%p= @car.user.email
				= link_to "Delete car", car_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"
				= link_to "Edit car", edit_car_path, class: "btn btn-default"
				= link_to "New Booking", new_car_booking_path(@car), class: "btn btn-primary"

			- @bookings.each do |booking|
				.panel-footer
					.row
						.col-md-6
							.btn-group.pull-right								
								%h3= booking.customer_name 
								= booking.comment 
								Pick Up Date: 
								%h4= booking.booked_from.strftime("%F")
								Drop Off Date:
								%h4= booking.booked_to.strftime("%F")
								created by:
								= booking.user.email
								Price:
								-case @car.category_id
								-when 1
									=(booking.booked_to-booking.booked_from).to_i*100
								-when 2
									=(booking.booked_to-booking.booked_from).to_i*75
								-else
									=(booking.booked_to-booking.booked_from).to_i*50
								zł
								%p= link_to "Delete booking", [booking.car, booking], method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title Rent a car
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags

%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand Rent a Car
			%ul.nav.navbar-nav
				%li= link_to "All Cars", root_path
				- Category.all.each do |category|
					%li= link_to category.name, cars_path(category: category.name)
			
			- if user_signed_in?
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "New Car", new_car_path
					%li= link_to "Account", edit_user_registration_path
					%li= link_to "Sign Out", destroy_user_session_path, method: :delete
			- else
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "Sign Up", new_user_registration_path
					%li= link_to "Sign In", new_user_session_path
	.container
		- flash.each do |name, msg|
			=content_tag :div, msg, class: "alert alert-info"
		= yield